# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a97e3bbf271dd4023de6b5b953abfb7e865c0e37651d9686fb2dceef22f7951c7c3a8b936b3708d9bf472cc889d3a98aa8e360a1c39b3c868064cc875ae51a46

test:
  secret_key_base: 79ac7c82d08143297310b40795e42c857385a45373a50abfd803e669ba02a4f9d08237a8a5160fea4c0e362863b90ab0224228054623d98c32fa4b4ddb44bc72

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
